""" Collect all constants of the REQPY package"""

# REQPY FILES
DEFAULT_REQPY_FILE_EXTENSION = ".yml"

# REPORT FILES
DEFAULT_REPORT_EXTENSION = ".md"

# DEFAUKT REQUIREMENT NAME
DEFAULT_REQ_NAME = "new_requirement"
